formatter: markdown

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  module "cloudrun_ai_app" {
    source  = "openteams-ai/cloudrun-ai-app/gcp"
    version = "~> 1.0"

    project_id     = "my-gcp-project"
    region         = "us-central1"
    customer_name  = "acme-corp"
    domain_name    = "acme.example.com"

    # Application configuration
    app_image      = "gcr.io/my-project/ai-app:latest"
    app_env_vars   = {
      AI_BACKEND_URL = "https://api.openai.com/v1"
      MCP_SERVER_URL = "https://mcp.example.com"
    }
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
