formatter: markdown

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  module "pocketbase_stack" {
    source  = "github.com/openteams-ai/terraform-pocketbase-gcp-deploy"

    project_id    = "my-gcp-project"
    region        = "us-central1"
    name_prefix   = "myapp-dev"
    base_domain   = "example.com"
    cookie_domain = ".example.com"
  pocketbase_image     = "us-docker.pkg.dev/myproj/images/pocketbase:fuse"
  enable_frontend_service = true
  frontend_image          = "us-docker.pkg.dev/myproj/images/web:latest"
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
